services:
  postgres:
    image: postgres:15-alpine
    container_name: h8-phase2-gc02-postgres-prod
    environment:
      POSTGRES_DB: ${DB_NAME:-h8_phase2_gc02}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_NAME:-h8_phase2_gc02}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: ${DOCKER_IMAGE:-app:latest}
    container_name: h8-phase2-gc02-app-prod
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: ${PORT:-8002}
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - "${PORT:-8002}:${PORT:-8002}"
    volumes:
      - ~/app/logs:/app/logs
    networks:
      - default
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8002}/health"]
      interval: 10s
      timeout: 3s
      start_period: 10s
      retries: 3

networks:
  default:
    name: app_default
    driver: bridge

volumes:
  postgres_data:
