services:
  postgres:
    image: postgres:15-alpine
    container_name: h8-phase2-gc02-postgres-dev
    environment:
      POSTGRES_DB: ${DB_NAME:-h8_phase2_gc02}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - h8-phase2-gc02-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: Dockerfile
      target: development
    container_name: h8-phase2-gc02-app-dev
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-8002}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-h8_phase2_gc02}
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-here-dev}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-your-super-secret-jwt-refresh-key-here-dev}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-15m}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN:-7d}
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      LOG_FILE: ${LOG_FILE:-true}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:8002}
      RATE_LIMIT_WINDOW_MS: ${RATE_LIMIT_WINDOW_MS:-900000}
      RATE_LIMIT_MAX_REQUESTS: ${RATE_LIMIT_MAX_REQUESTS:-100}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME:-your-cloudinary-cloud-name}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY:-your-cloudinary-api-key}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET:-your-cloudinary-api-secret}
    ports:
      - "${PORT:-8002}:${PORT:-8002}"
    volumes:
      - ../src:/app/src:ro
      - ../scripts:/app/scripts:ro
      - ../logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - h8-phase2-gc02-network
    restart: unless-stopped

networks:
  h8-phase2-gc02-network:
    driver: bridge

volumes:
  postgres_data:
